[project]
name = "rag-test-max"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.3",
    "openai==0.28",
    "pandas>=2.2.3",
    "sentence-transformers>=4.0.2",
    "streamlit>=1.44.1",
]
